# Generated by Django 3.0.7 on 2020-11-28 10:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='ФИО')),
                ('position', models.CharField(max_length=500, verbose_name='Должность')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Контент')),
                ('image', models.ImageField(blank=True, upload_to='management', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Руководство Центра',
                'verbose_name_plural': 'Руководство Центра',
            },
        ),
    ]
