# Generated by Django 3.0.7 on 2020-11-28 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='management',
            old_name='image',
            new_name='image_title',
        ),
        migrations.CreateModel(
            name='GalleryManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='management', verbose_name='Фотогаллерея')),
                ('main_image', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='management.Management')),
            ],
        ),
    ]
