# Generated by Django 3.0.7 on 2020-11-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20201128_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='main_card',
            field=models.BooleanField(default=False, verbose_name='Директор'),
        ),
    ]
