# Generated by Django 3.0.9 on 2020-11-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_gallerynews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerynews',
            name='in_the_title',
        ),
        migrations.AddField(
            model_name='news',
            name='image_title',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
