# Generated by Django 3.0.9 on 2020-11-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='implink',
            name='link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='implink',
            name='content',
            field=models.CharField(blank=True, max_length=500, verbose_name='Контент'),
        ),
    ]
