# Generated by Django 3.1.1 on 2020-11-27 17:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='ФИО')),
                ('position', models.CharField(max_length=500, verbose_name='Должность')),
                ('slogan', models.CharField(max_length=500, verbose_name='Слоган')),
                ('education', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Образование')),
                ('working_activity', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Трудовая деятельность')),
                ('additionally', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Дополнительные сведения о кандидате')),
                ('image', models.ImageField(blank=True, upload_to='doctors', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Московский врач',
                'verbose_name_plural': 'Московский врач',
            },
        ),
    ]
