# Generated by Django 3.0.7 on 2020-12-04 06:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Know',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Это нужно знать',
                'verbose_name_plural': 'Это нужно знать',
                'ordering': ['title'],
            },
        ),
    ]
