# Generated by Django 3.0.7 on 2020-12-04 09:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Контент')),
                ('image_title', models.ImageField(blank=True, upload_to='video', verbose_name='Фото обложки')),
            ],
            options={
                'verbose_name': 'Видеоролик',
                'verbose_name_plural': 'Видеоролики',
            },
        ),
    ]
