# Generated by Django 3.0.7 on 2020-12-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regularPages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regularpage',
            options={'verbose_name': 'Статическую страницу', 'verbose_name_plural': 'Статические страницы'},
        ),
    ]
