# Generated by Django 3.0.7 on 2020-11-19 15:50

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('address', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Адрес')),
                ('phones', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Телефоны')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='Specialists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('division', models.CharField(blank=True, max_length=300, verbose_name='Подразделение (Наименование)')),
                ('job', models.CharField(blank=True, max_length=200, verbose_name='Штатная должность (Наименование)')),
                ('vyz', models.CharField(blank=True, max_length=300, verbose_name='ВУЗ')),
                ('date_vyz', models.CharField(blank=True, max_length=100, verbose_name='Дата окончания')),
                ('profession', models.CharField(blank=True, max_length=200, verbose_name='Специальность')),
                ('sertif', models.CharField(blank=True, max_length=100, verbose_name='Сертификат')),
                ('date_sertif', models.CharField(blank=True, max_length=100, verbose_name='Дата выдачи')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('degree', models.CharField(blank=True, max_length=100, verbose_name='Степень')),
                ('keyBranches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist', to='structure.Branches', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
        migrations.CreateModel(
            name='GalleryBranches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='branches/', verbose_name='Фото/Схема проезда')),
                ('in_the_cont', models.BooleanField(default=False, verbose_name='В основной контент')),
                ('location_map', models.BooleanField(default=False, verbose_name='Схема проезда')),
                ('keyBranches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='structure.Branches')),
            ],
        ),
    ]
