# Generated by Django 3.0.7 on 2020-11-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerybranches',
            name='in_the_cont',
        ),
        migrations.AddField(
            model_name='branches',
            name='image_title',
            field=models.ImageField(blank=True, upload_to='branches/', verbose_name='Фото заголовка'),
        ),
    ]
