# Generated by Django 3.0.9 on 2020-12-07 06:44

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20201123_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branches',
            name='address',
        ),
        migrations.RemoveField(
            model_name='branches',
            name='email',
        ),
        migrations.RemoveField(
            model_name='branches',
            name='phones',
        ),
        migrations.AddField(
            model_name='branches',
            name='contacts',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Контактная информация'),
        ),
    ]
